### ISSUE TITLE
Documentation: Add Cloudflare R2 as S3 Provider

### ISSUE THREAD

**Issue by kotx** [owncast/owncast#2138] opened 2022-09-24 05:23 UTC
### Share your bug report, feature request, or comment.

[Cloudflare R2](https://www.cloudflare.com/products/r2/) does not charge for egress, only operations (that are classified as A or B, which are priced differently). Adding this to the documentation as an [S3 provider](https://owncast.online/docs/storage/) would be useful.

**Comment by unclebinary1001** [comment] 2022-09-28 06:37
Hey, I would like to work on this. Could you assign this to me?

**Comment by gabek** [comment] 2022-09-28 14:23
Yes, thank you!

**Comment by unclebinary1001** [comment] 2022-10-06 08:44
@gabek 

I was able to write up instructions for creating an R2 bucket with Cloudflare, configuring api token permissions, and setting up a cors policy for file sharing.

With my local installation of Owncast, live streaming appears to function well without S3 storage enabled as I streamed from OBS Studio.

When I tried to test with S3 storage enabled, I'm getting a static image of my stream without live button and play button isn't working. Do I only need an empty bucket and point to it as my endpoint for streaming across S3 storage to work? Do I then have to add video files to my bucket? Is there anything else I will need so I can test.

**Comment by gabek** [comment] 2022-10-06 15:53
If after turning on S3 with R2 video playback doesn't work it sounds like something is wrong. Take a look at your browser console for errors, as well as in the Owncast admin `/admin` for errors.

**Comment by gabek** [comment] 2022-10-12 22:05
Hi @unclebinary1001! Just checking in to see if you've been able to troubleshoot your S3 config.

**Comment by unclebinary1001** [comment] 2022-10-12 22:17
@gabek 
The error I was getting in my console is: `Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://*<ACCOUNT_ID>*.r2.cloudflarestorage.com/cast/*<OBJECT>*. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 400` 

 The thing is, R2 buckets have an issue with CORS configuration.
The S3 API token I generated through the API token section in Cloudflare is working and connecting correctly.
I tried configuring bucket cors using the AWS client on js in node, and I am getting a 200 status code. Still, the problem is that whenever I run a request, I get the Access to HTML Request failed in my console Allow-Access-Control-Origin header missing in response.
Cloudflare announced the added cors configuration to the bucket on [09/28/2022](https://developers.cloudflare.com/r2/platform/changelog/) using the PUT request to `<account_id>.storage.Cloudflare.com/<bucket_name>/?cors` using the XML cors configuration, but it doesn’t affect my request.

I have since joined the Cloudflare developer discord channel to make sure I follow up on this problem. It seems like a lot of people are currently having issues with this.

I will continue monitoring the r2-storage channel to see if any better solution arises.

Also, I am open to sharing my progress and findings if anyone may want to take this up. I remain interested in completing this task.

**Comment by gabek** [comment] 2022-10-12 22:24
Thank you for the detailed update! It sounds like R2 isn't yet compatible as a S3 provider until they fully support CORS. No big deal. Some day when they fix it can add it to the list of providers :)

**Comment by rmens** [comment] 2023-03-01 19:31
According to the changelog for R2 it seems like CORS is supported since 23/01/2023. Are you still willing to document this @unclebinary1001? If not, I could give it a shot too. https://developers.cloudflare.com/r2/learning/cors/

<blockquote><img src="https://developers.cloudflare.com/dev-products-preview.png" width="48" align="right"><div><img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAACXBIWXMAAAsSAAALEgHS3X78AAADW0lEQVRYw+2WS0hUURjHZ+aGkQTRJuih18kCIXBZLdRx1JYtQpNIggijFlFgSFmZd0ynTO2xDYraRKTmo7KoqE27aFOLSKJ3tMmNd0bn3nl8/b9zz505jo8yhTZz4Md359zH//993zn3jseTG7mxwBFt93sioSJxzFGFx3jzWk+kvWjphVUReewzDV0DXrNN9yD6MKcB70Q3TBqZ65dE3MyIs7B33usNYSR9L3X6Fylu6O6xpswHQBcYBKPgBjgIVvN5NqmaWJQBVRxRZ0HrXBFR10ai834HPr7gJ5z7CfbztRNnCz0LMuH0Vlf7zKVcxsi5EhZgMWSYjBi6jd9xkOCIubjV4RjD7za1EhFZxfnFjUyfZzm/HLzlbBEtkBIYesp0j0NFfC7B5mQ16sW94WLN7qtIP8seCMw0oPTZK+NKsA8cB5s50kWRuS2EIKyIUiTLRLxTGBiLhjfl8fNit7ZpENZccas/MNOImzmiH7zjLGQmnLEZbXeETM7amCZO2UZwTSIBE9iiO7OThbDQifWVT1tkYi/L44fULbK1uK9RPNgVV0RoTgNudQydor0lx+yh4G2rv+IOhBtBvlOBCl/2PncX2gowEXUellRKuxDiKawVs7XglXW3/Cg9qyEarSJ6VEUw8AGUiUqwCRYPa2kjq8BuMBWdXs7kXyKunUS1qKeYzJZ19fZw8Co9qSZkHAExGgmyiTjYnt3/ZvBrUukzRzbCvXThxRXHVmNsCW89fi/EJLgvhu/BSZnlARquJBoBD4KUuBcQEQbexLEoXfEO7jnfLIWFCWnGBNfAZdADwiAEzoAToAkcAYfkm7ABvV+TtejKQBNoAS+EifvCxC4WL1UyTmT1kuSL5gf4Lvmm8FXyBXwGn8B70CgW2s2teRAJgddgDHwE49wCelzNBnrZQAtvNRiI4S2YlAtP9FTGVEwprzUXHc55sW0NnauWD4EBelrjlH/YgbPHvMWLEvE6G7hCl4ppCuWOd86C0us/IQzw9m0teGn1lR+m5zucng9lDDDJQczhHFfHfb/vRaa1iHX/Cu7nyM9oME+tL8Xe34JV3wBqQR3E6iwgovN7Dyj8/3+x+N3PXz3+dyO/fovGPL3BZw9WepGpxshvQBplzpv7k5sbuZEbvwGDMvjj7QjeVAAAAABJRU5ErkJggg==" height="14"> Cloudflare Docs</div><div><strong><a href="https://developers.cloudflare.com/r2/learning/cors/">Configure CORS · Cloudflare R2 docs</a></strong></div><div>Cross-Origin Resource Sharing (CORS) is a standardized method that prevents domain X from accessing the resources of domain Y. It does so by using …</div></blockquote>

**Comment by unclebinary1001** [comment] 2023-03-01 19:44
Hey, thank you for letting me know about this. At the time there was
speculation about CORS being enabled on R2. I'm glad to know it's finally
rolled out into production. I can pick up from where I left off. I'll let
you know if I run into any issues.

**Comment by unclebinary1001** [comment] 2023-03-03 07:50
Hi all, I was able to finally setup owncast to serve streaming clients from a Cloudflare R2 bucket. I have raised a pull request for review [here](https://github.com/owncast/owncast.github.io/pull/112). 

Thank you for the tip on the new feature roll out for CORS configuration @rmens

**Comment by rmens** [comment] 2023-03-03 10:33
Hey @unclebinary1001, I have proof-read your instructions. They are very clear. Great! Just some small spelling and capitalization mistakes I have put in comments.

**Comment by gabek** [comment] 2023-03-03 18:59
> Hey @unclebinary1001, I have proof-read your instructions. They are very clear. Great! Just some small spelling and capitalization mistakes I have put in comments.

I can't seem to find your comments. Did you add them inline in the PR, as a comment of the PR itself, or somewhere else?

**Comment by rmens** [comment] 2023-03-03 19:07
I added them inline to the PR as review.

But when I open the PR in a private window, I don't see them either. I'm not sure if these are only visible to the author of the PR and the reviewer or not. 

How shall I proceed. Just copy and paste the line numbers and comments here too?

**Comment by unclebinary1001** [comment] 2023-03-03 19:08
@rmens I also can't seem to find the comments you left. I'm happy to make the necessary edits as soon as I see the feedback.

**Comment by rmens** [comment] 2023-03-03 19:09
Sorry guys I missed the "submit review" button. They are visible now.

**Comment by unclebinary1001** [comment] 2023-03-03 19:21
Thanks! I now see the comments. I'll raise a PR once I get back to my
computer.

**Comment by rmens** [comment] 2023-03-03 19:28
Thanks. In the meantime I followed the instructions and integrated this on my Owncast Nightly. Chunks are being uploaded, but it's not working yet. 

I think the requests served over Cloudflare are missing a `content-type: application/x-mpegURL` header. Causing them to display as plain text in the browser and not working in the player. For example this is a variant of my stream on R2

```
curl -I "https://hls.zuidwesttv.nl/hls/2/stream.m3u8"
HTTP/1.1 200 OK
Date: Fri, 03 Mar 2023 19:21:18 GMT
Content-Length: 1063
Connection: keep-alive
Accept-Ranges: bytes
Cache-Control: max-age=0
ETag: "13c6968c6bd856b4c0fb1df664b4bd4b"
Last-Modified: Fri, 03 Mar 2023 19:21:16 GMT
Vary: Accept-Encoding
CF-Cache-Status: DYNAMIC
Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=3dPAHPNRY0bwALz6fBiG%2BM48D8zWHfkpn5UAgGH9suaDGeqioUpL%2BqOZdtiFzMUaR958waRC559ePwtvTkY0Q2xuDpOo5EntLrcVUul%2Bt6IS10k%2Bm5QRyXCQ5dre06z6GFQOrQ%3D%3D"}],"group":"cf-nel","max_age":604800}
NEL: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
Server: cloudflare
CF-RAY: 7a243de1cf040a49-AMS
alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400
```

And this is Owncast itself

```
curl -I "https://live.zuidwesttv.nl/hls/2/stream.m3u8"
HTTP/2 200 
accept-ranges: bytes
access-control-allow-origin: *
alt-svc: h3=":443"; ma=2592000
cache-control: no-cache, no-store, must-revalidate
content-type: application/x-mpegURL
date: Fri, 03 Mar 2023 19:21:25 GMT
expires: Thu, 1 Jan 1970 00:00:00 GMT
last-modified: Fri, 03 Mar 2023 19:21:25 GMT
server: Caddy
content-length: 1073
```

This isn't something that can be fixed with documentation. So I raised this as a bug here https://github.com/owncast/owncast/issues/2771. It is however a blocker for releasing documentation which implies official support for R2.

**Comment by rmens** [comment] 2023-03-03 20:10
I dug into auto-deletion too. This is not possible with R2 currently.

Here is a mapping of supported S3 functions on R2. Object Lifecycles isn't one of them. So we seem to be on our own deleting old hls chuncks. https://developers.cloudflare.com/r2/data-access/s3-api/api/

However Cloudflare seems to be [working on it](https://blog.cloudflare.com/r2-ga/).

> What’s next?
> 
> Making R2 generally available is just the beginning of our object storage journey. We’re excited to share what we plan to build next.
> 
> Object Lifecycles
> 
> In the future R2 will allow developers to set policies on objects. For example, setting a policy that deletes an object 60 days after it was last accessed. Object Lifecycles pushes object management down to the object store.

Found this topic on the CF Community that describes a workaround for now https://community.cloudflare.com/t/delete-objects-from-r2-bucket-older-than-a-date/470812

**Comment by gabek** [comment] 2023-03-04 00:42
@unclebinary1001 How was R2 working for you given the above mentioned content type issue?

**Comment by unclebinary1001** [comment] 2023-03-04 02:14
@gabek So, following the steps in the doc and using a managed subdomain under Cloudflare as a serving endpoint. Streaming over my localhost on a localhost owncast instance is working fine. 

I used tried to make a request to the serving endpoint using the terminal. 

The content-type in the response seems to be `video/mp2t`  like below:


![curl-cloudflare-r2-response](https://user-images.githubusercontent.com/69122375/222870400-d33fb38d-28a0-477c-9ef8-17bb133fd2d3.png)

**Comment by rmens** [comment] 2023-03-04 13:31
@unclebinary1001 @gabek Yes. I can reproduce that the video chucks are getting the correct header.

```
curl -I "https://hls.zuidwesttv.nl/hls/2/stream-QvAY7ybVg-1005.ts"
HTTP/1.1 200 OK
Date: Sat, 04 Mar 2023 13:26:40 GMT
**Content-Type: video/mp2t**
Content-Length: 410968
Connection: keep-alive
Accept-Ranges: bytes
Cache-Control: max-age=31557600
ETag: "9364d2b60a6ebe724c9a9e251c27c816"
Last-Modified: Fri, 03 Mar 2023 19:48:21 GMT
Vary: Accept-Encoding
CF-Cache-Status: DYNAMIC
Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=0ndzbJTpOvEWunCxg2A4cL6xjJQz6Qa1BfKd8RPoKOtMbWp141N%2BWwpeseq05%2FUu9ztWWsYfxOsyBArhrfuCyQpEAi8ZkVpvBUY2aOHTOJklHm7ArNXXPrjwlK%2BJR2lNcTOnuw%3D%3D"}],"group":"cf-nel","max_age":604800}
NEL: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
Server: cloudflare
CF-RAY: 7a2a73c9b87fb7df-AMS
alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400
```

But the m3u8 files aren't. I checked your R2 stored m3u8 too, which shows up in my browser as plain text and not a video.
```
curl -I https://pub-9d4ab9a0f7fa43e991edd0ddd2545c78.r2.dev/hls/0/stream.m3u8
HTTP/1.1 200 OK
Date: Sat, 04 Mar 2023 13:27:59 GMT
Content-Length: 1138
Connection: keep-alive
Accept-Ranges: bytes
Cache-Control: max-age=0
ETag: "5acaaeb364119832be508a8008d74666"
Last-Modified: Sat, 04 Mar 2023 02:27:30 GMT
Server: cloudflare
CF-RAY: 7a2a75b169810eb3-AMS
```
For me this leads to Owncast not being able to play the video at all. Is it playing for you on the Owncast page of your instance?

**Comment by unclebinary1001** [comment] 2023-03-05 04:58
@rmens My video is able to play. I am using OBS studio to stream, a local-hosted instance of Owncast to make the streaming service connection, and a local-host client to stream the video. 

I think .m3u8 files are supposed to be [plain-text](https://www.easeus.com/knowledge-center/m3u8.html#:~:text=Final%20Thoughts-,What%20Is%20an%20M3U8%20File%3F,media%20file%20or%20a%20folder.)

Also, can you share any errors that might be showing up in the console on your browser client? Mine shows no errors when I play the stream; so some helpful information might be showing up.

**Comment by rmens** [comment] 2023-03-05 14:05
@unclebinary1001 I was finally able to figure it out. The `content-type` headers didn't turn out to be the culprit but the Serving Endpoint was. I didn't use the r2.dev domain name but made a CNAME for my own domain. I entered it as:

- https://hls.domain.ltd/ 

In the owncast Serving Endpoint field. However it needed to be:

- https://hls.domain.ltd

Without the trailing slash. It resulted in a double `//` in the generated urls, which Cloudflare R2 doesn't normalize and resulted in 404's. It might be good to save others a wild goose chase and make a remark about this in the documentation.

Besides this mistake, your instructions were complete and got streaming with R2 working. So I think this is clear and good for publication.

**Comment by unclebinary1001** [comment] 2023-03-05 18:16
> @unclebinary1001 I was finally able to figure it out. The `content-type` headers didn't turn out to be the culprit but the Serving Endpoint was. I didn't use the r2.dev domain name but made a CNAME for my own domain. I entered it as:
> 
> * https://hls.domain.ltd/
> 
> In the owncast Serving Endpoint field. However it needed to be:
> 
> * https://hls.domain.ltd
> 
> Without the trailing slash. It resulted in a double `//` in the generated urls, which Cloudflare R2 doesn't normalize and resulted in 404's. It might be good to save others a wild goose chase and make a remark about this in the documentation.
> 
> Besides this mistake, your instructions were complete and got streaming with R2 working. So I think this is clear and good for publication.

@rmens Great! I've added a warning to not include a trailing slash in the serving endpoint url in the updated pr. Thank you for catching that.

**Comment by rmens** [comment] 2023-03-05 19:19
@unclebinary1001 Awesome! I did some calculations on the requests. 

With 4 stream variants (360p, 480p, 720p and 1080p) this causes about 10k Class A requests per hour. In the R2 free tier there are 1 million Class A requests per month included. That **makes the first 100 hours of streaming completely free** when using the same variants as Twitch offers.

For streaming 24/7 it's about 7,5 million Class A requests. The first million are free. Which results in about 6,5 million paid requests. At $4,50 per million requests, that's about ~$29/month for a CDN with no bandwidth limits (R2 only charges for Class A and Class B requests). Sound like a sweet deal to me.

Class B requests are hardly used by Owncast, and 10 million are included. I don't expect that limit to ever be hit.

**Comment by gabek** [comment] 2023-03-05 23:16
> I think .m3u8 files are supposed to be [plain-text](https://www.easeus.com/knowledge-center/m3u8.html#:~:text=Final%20Thoughts-,What%20Is%20an%20M3U8%20File%3F,media%20file%20or%20a%20folder.)

There's a few content types, but `application/x-mpegurl` is one of the accepted ones. I could see many scenarios where the player doesn't care of the actual content type, however, because it's expecting a m3u8 playlist so it'll treat it like it is. I think that's what we're seeing most of the time.

> @rmens Great! I've added a warning to not include a trailing slash in the serving endpoint url in the updated pr. Thank you for catching that.

I went ahead and filed a TODO to strip the trailing slash.

**Comment by rmens** [comment] 2023-03-08 12:03
After testing this for 72+ hours uninterrupted I think this can be considered stable enough.

The only thing that's missing is an expiration policy for files. My R2 Bucket was filled with about 400GB of chunks. Cloudflare R2 doesn't have the option to let files expire yet. 

A quick fix for me was running a cronjob on my webserver with a small php script that deletes files older than an hour, except for `.m3u8` files and `offline.ts` files. @gabek do you think adding a warning to the documentation that file expiration is currently missing on R2 is enough to publish it, or is it better to wait for object lifecycle support in R2?

**Comment by gabek** [comment] 2023-03-08 20:17
Thanks so much for testing, @rmens! I think that's a really good idea about adding a warning.

Personally I probably wouldn't use a storage provider that doesn't support object lifecycles because the downside is so huge of paying for more storage than needed in the long term, unless you go out of your way like you did to wire up some kind of manual deletion. So a warning would make a lot of sense.

**Comment by gabek** [comment] 2023-03-08 20:20
Since it's becoming a larger issue for people due to more providers that can cause financial damage I went ahead and planned work on #2646.

**Comment by rmens** [comment] 2023-03-10 20:56
With it properly tested, all the typo's I reported fixed and the warning added for no object expiration policy this shaped up really nice. Great work @unclebinary1001. This is ready to be merged imho, or is there anything you'd like to have changed or tested @gabek? (I need to quit testing on R2 soon because it's getting expensive)

**Closed as completed** 2023-03-10 20:57 UTC
Labels: documentation, help wanted, good first issue, backlog
