### ISSUE TITLE
manifest.json data difference between data set in admin dashboard eg. logo , website name and etc.

### ISSUE THREAD

**Issue by moonshadowrev** [owncast/owncast#3617] opened 2024-03-06 08:56 UTC
### Share your bug report, feature request, or comment.

as i mentioned in title , when you change logo and everything , manifest of system won't be updated 
when user adds stream to enable notification for mobilephones like iPhone , manifest.json generates title and logo 

/manifest.json
```json
{
 "name": "Owncast",
 "icons": [
  {
   "src": "\/img\/favicon\/android-icon-36x36.png",
   "sizes": "36x36",
   "type": "image\/png",
   "density": "0.75"
  },
  {
   "src": "\/img\/favicon\/android-icon-48x48.png",
   "sizes": "48x48",
   "type": "image\/png",
   "density": "1.0"
  },
  {
   "src": "\/img\/favicon\/android-icon-72x72.png",
   "sizes": "72x72",
   "type": "image\/png",
   "density": "1.5"
  },
  {
   "src": "\/img\/favicon\/android-icon-96x96.png",
   "sizes": "96x96",
   "type": "image\/png",
   "density": "2.0"
  },
  {
   "src": "\/img\/favicon\/android-icon-144x144.png",
   "sizes": "144x144",
   "type": "image\/png",
   "density": "3.0"
  },
  {
   "src": "\/img\/favicon\/android-icon-192x192.png",
   "sizes": "192x192",
   "type": "image\/png",
   "density": "4.0"
  }
 ],
 "display": "fullscreen"
}
```

**Comment by gabek** [comment] 2024-03-06 17:49
Duplicate of #2995.

**Closed as not planned by gabek** 2024-03-06 17:49 UTC
