### ISSUE TITLE
Support disabling inbound chat message rate limiter

### ISSUE THREAD

**Issue by SearingEchoes** [owncast/owncast#3523] opened 2024-01-17 03:53 UTC
I'm running my own private stream server and I'm the admin, but for some reason there's seemingly no way to turn off whatever this anti-chat-spam protection is. I really don't want it and would like to disable it on a per-user basis or system-wide.

**Comment by armadi1809** [comment] 2024-01-17 20:59
@gabek it this is something you are interested in implementing, I would be happy to take a look.

**Comment by gabek** [comment] 2024-01-19 05:49
There's an entire discussion about this here somewhere, but I can't find it right now. I'll try to find it later.

**Comment by gabek** [comment] 2024-01-19 23:38
In short, there's no way to turn this off. It works for 95+% of the people. So instead of having yet _another_ toggle making the Owncast admin even more complicated than it already is, if users of Owncast are collectively unhappy with the value that it's set as, we should find a better one.

I know from your standpoint you're thinking "just add another switch, what's the big deal?" but a lot of switches and settings are starting to add up, and it's starting to cause cognitive overhead. So adding a feature that will only be useful to a small group of people, but make it look like Owncast is more complicated to all people, isn't a fair tradeoff.

If the feature isn't working as designed (though it seems to be for most people) it should be fixed, however. Or some kind of implicit setting like all moderators don't have flood protection or something. But again, this isn't a problem most people have, so it would have to be a low lift solution that doesn't get in the way or make things complicated.

**Comment by SearingEchoes** [comment] 2024-01-21 13:28
I'll put it this way, I can't even chat with users over text because pretty much every time I get blocked, even with moderator status. I love the software, it's great. But it's genuinely frustrating when I can't do something as basic as use the chat because I get blocked all of the time.

**Comment by gabek** [comment] 2024-01-21 15:37
I understand you're frustrated, that's why I was trying to work with you, and I was offering up possible solutions above. You said the moderator idea wouldn't work. Why not? It sounds like you're also not willing to suggest updated values either, why is that?

Additionally, one thing to ask in times like this is, if others are having an ok experience, and you're not, let's figure out what you're doing differently, and see if anything can be done to improve everyone's experience if there are improvements there. But it sounds like you're having problems, most people are not. Do you know why?

**Comment by SearingEchoes** [comment] 2024-01-23 14:14
> I understand you're frustrated, that's why I was trying to work with you, and I was offering up possible solutions above. You said the moderator idea wouldn't work. Why not? It sounds like you're also not willing to suggest updated values either, why is that?
> 
> Additionally, one thing to ask in times like this is, if others are having an ok experience, and you're not, let's figure out what you're doing differently, and see if anything can be done to improve everyone's experience if there are improvements there. But it sounds like you're having problems, most people are not. Do you know why?

I'm genuinely confused as to why you'd assume that I'm not willing to suggest updated values, I am. I'm just not even sure what they are in the first place.

For context I use Owncast to host a private dev stream for the development of a game I'm making, and I don't always communicate with chat via my Microphone/Talking, I'll send several messages within a span of a 20 seconds or less depending on what I'm saying. I'm unable to do this because I get blocked from chatting after a couple of messages, cutting me off from finishing something I'm trying to say because I'm typing too fast, triggering the anti-spam.

> You said the moderator idea wouldn't work.

I did not say that.

When I referred to the moderator status, I meant that having moderator status didn't prevent me from being temporarily blocked from chatting, I think having moderators exempt from it or a setting would be quite handy.

> So instead of having yet another toggle making the Owncast admin even more complicated than it already is

I respectfully disagree on this point, I don't really find the admin page complicated at all, it's pretty simple compared to quite a few other admin panels for self-hosted software (phpBB, WordPress, Wiki.js, Mediawiki etc) and quite nice, so definite kudos to the team on that. I still think there should be a way to toggle the anti-spam off if the host wants it off though.

**Closed as completed** 2024-04-10 05:25 UTC
Labels: enhancement, Web frontend, chat, API, admin, go backend
