### ISSUE TITLE
Self-hosted Owncast directory

### ISSUE THREAD

**Issue by georgesmith9914** [owncast/owncast#1928] opened 2022-05-26 06:48 UTC
I would like to self-host Owncast directory similar to https://directory.owncast.online/ . Is this currently possible? In case not, can you please consider this feature request?

Thanks a lot.

**Comment by gabek** [comment] 2022-05-26 06:54
It's not something that's currently possible. If communities of Owncast streamers ever become a bigger thing then I'd like to bubble this work up, but for now it's something that's low priority.

Of course there's nothing stopping you from building your own directory like was done here: https://codeberg.org/yarmo/ownroll.

Closing as a duplicate of #1143

<blockquote><img src="https://codeberg.org/avatars/c7d7a0cdfed3f77b20e0367b523ef3f2" width="48" align="right"><div><img src="https://design.codeberg.org/logo-kit/favicon.svg" height="14"> Codeberg.org</div><div><strong><a href="https://codeberg.org/yarmo/ownroll">ownroll</a></strong></div><div>Selfhosted Owncast directory written in Rust</div></blockquote>

**Closed as not planned by gabek** 2022-05-26 06:54 UTC
