### ISSUE TITLE
Unknown pixel format requested: vaapi_vld on a system with working h264_vaapi codec

### ISSUE THREAD

**Issue by VladimirAkopyan** [owncast/owncast#2729] opened 2023-02-24 03:13 UTC
### Jellyfin works, owncast doesnt

I have an Ubuntu 22 Server, with I3 8100. I have VA API v1.12 with Intel iHD Driver v21.1.3
I am using the h264_vaapi codec in Jellyfin to transcode video, and I can confirm it's working on the GPU with intel_gpu_top and with logs

<img width="754" alt="image" src="https://user-images.githubusercontent.com/12278048/221082501-e0997450-6f41-4053-b666-f2cd26889131.png">

I am wondering if it's my setup or something in Owncast

Jellyfin command, this works:
```BASH
/usr/lib/jellyfin-ffmpeg/ffmpeg -analyzeduration 200M -ss 00:02:36.000 -init_hw_device vaapi=va:,driver=iHD -filter_hw_device va -hwaccel vaapi -hwaccel_output_format vaapi -autorotate 0 -i [file:"/mnt/hdd/Movies/300.2006.1080p.DTS.Badkokos.mkv](file://%22/mnt/hdd/Movies/300.2006.1080p.DTS.Badkokos.mkv)" -autoscale 0 -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 h264_vaapi -rc_mode VBR -b:v 7360000 -maxrate 7360000 -bufsize 14720000 -profile:v:0 high -force_key_frames:0 "expr:gte(t,156+n_forced*3)" -vf "setparams=color_primaries=bt709:color_trc=bt709:colorspace=bt709,scale_vaapi=format=nv12" -codec:a:0 libfdk_aac -ac 6 -ab 640000 -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type mpegts -start_number 52 -hls_segment_filename "/var/lib/jellyfin/transcodes/63ce062a38f3dd4f89d5f8f035051833%d.ts" -hls_playlist_type vod -hls_list_size 0 -y "/var/lib/jellyfin/transcodes/63ce062a38f3dd4f89d5f8f035051833.m3u8"
```

Owncast Log, this crashes:
```BASH
/usr/lib/jellyfin-ffmpeg/ffmpeg -hide_banner -loglevel warning -vaapi_device /dev/dri/renderD128 -fflags +genpts -i ./data/tmp/offline.ts263601401 -map v:0 -c:v:0 h264_
vaapi -b:v:0 2808k -maxrate:v:0 3032k -g:v:0 150 -keyint_min:v:0 150 -r:v:0 30 -map "a:0?" -c:a:0 copy -sws_flags bilinear -filter:v:0 "scale=1080:720,format=nv12,hwupl
oad" -preset faster -var_stream_map "v:0,a:0 " -f hls -hls_time 5 -hls_list_size 5 -hls_flags program_date_time+independent_segments -hls_playlist_type event -segment_f
ormat_options "mpegts_flags=mpegts_copyts=1" -pix_fmt vaapi_vld -sc_threshold 0 -master_pl_name stream.m3u8 -hls_segment_filename "[http://127.0.0.1:35159/%v/stream-offl](http://127.0.0.1:35159/%25v/stream-offl)
ine-%d.ts" -max_muxing_queue_size 400 -method PUT "[http://127.0.0.1:35159/%v/stream.m3u8](http://127.0.0.1:35159/%25v/stream.m3u8)"
Input #0, mpegts, from './data/tmp/offline.ts263601401':
Duration: 00:00:08.09, start: 1.439333, bitrate: 1135 kb/s
Program 1
Metadata:
service_name    : Owncast Offline
service_provider: FFmpeg
Stream #0:0[0x100]: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(progressive), 854x480 [SAR 1:1 DAR 427:240], 24 fps, 24 tbr, 90k tbn
Stream #0:1[0x101](eng): Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 113 kb/s
Unknown pixel format requested: vaapi_vld.
```

Both use the same FFmpeg: 
```BASH
ffmpeg version 5.1.2-Jellyfin Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.4.0-1ubuntu1~20.04.1)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-libs=-lfftw3f --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-shared --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-static --enable-gmp --enable-gnutls --enable-chromaprint --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libdav1d --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libsvtav1 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-opencl --enable-vaapi --enable-amf --enable-libmfx --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
```

vainfo output:
```BASH
ffmpeg version 5.1.2-Jellyfin Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.4.0-1ubuntu1~20.04.1)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-libs=-lfftw3f --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-shared --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-static --enable-gmp --enable-gnutls --enable-chromaprint --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libdav1d --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libsvtav1 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-opencl --enable-vaapi --enable-amf --enable-libmfx --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
```

Devices:
```BASH
 ls -l /dev/dri
total 0
drwxr-xr-x  2 root root         80 Feb 24 01:29 by-path
crw-rw----+ 1 root video  226,   0 Feb 24 01:29 card0
-rw-r--r--  1 root root          0 Feb 24 03:09 log_20230224.log
crw-rw----+ 1 root render 226, 128 Feb 24 01:29 renderD128
```

**Comment by gabek** [comment] 2023-02-24 03:16
See #2071 for fixing support for ffmpeg 5 with vaapi.

**Comment by gabek** [comment] 2023-02-24 05:00
Closing as duplicate of #2071, feel free to open a new issue if you find different issues occurring with ffmpeg 4.

**Closed as not planned by gabek** 2023-02-24 05:00 UTC
