### ISSUE TITLE
FEATURE REQUEST : Disable the "x joined the chat" and "is now knows as" notifications

### ISSUE THREAD

**Issue by TomKamin1** [owncast/owncast#1711] opened 2022-01-30 19:55 UTC
Hey, trying Owncast with over 1000 people, i quickly found the notifications of new people joining etc can be very overwhelming, which is why im suggesting programming a checkmark to disable these two features (can be both at once, or each separately)

Thanks! 

Tom

**Comment by gabek** [comment] 2022-01-30 19:58
Closing join message request as a duplicate of #1582. Please visit that issue to track.

We do not plan on hiding name change messages, as that would be very confusing.

**Closed as completed by gabek** 2022-01-30 19:58 UTC
