### ISSUE TITLE
Unable to generate thumbnail: exit status 139

### ISSUE THREAD

**Issue by SkYNewZ** [owncast/owncast#463] opened 2020-12-16 13:08 UTC
Hi, I have this runtime error `Unable to generate thumbnail: exit status 139`. See nothing on documentation about this topic.

I'm testing this project using a downloaded YouTube video.

```
root@foo:/etc/caddy/caddy.conf.d# journalctl -f -u owncast
-- Logs begin at Mon 2020-12-14 21:32:49 CET. --
Dec 16 14:03:04 foo owncast[26593]: time="2020-12-16T14:03:04+01:00" level=debug msg="Your instance can be listed on the Owncast directory at http://directory.owncast.online by enabling YP in your config.  Learn more at https://directory.owncast.online/get-listed."
Dec 16 14:03:04 foo owncast[26593]: time="2020-12-16T14:03:04+01:00" level=info msg="Web server is listening on port 8081, RTMP is accepting inbound streams on port 1935."
Dec 16 14:03:04 foo owncast[26593]: time="2020-12-16T14:03:04+01:00" level=info msg="The web admin interface is available at /admin."
Dec 16 14:03:04 foo owncast[26593]: time="2020-12-16T14:03:04+01:00" level=trace msg="Web server running on port: 8081"
Dec 16 14:03:04 foo owncast[26593]: time="2020-12-16T14:03:04+01:00" level=trace msg="Starting the websocket listener on: /entry"
Dec 16 14:03:04 foo owncast[26593]: time="2020-12-16T14:03:04+01:00" level=trace msg="RTMP server is listening for incoming stream on port: 1935"
Dec 16 14:03:14 foo owncast[26593]: time="2020-12-16T14:03:14+01:00" level=trace msg="0xc001b5e900 <REDACTED>:1935 <REDACTED>:46960 Connected"
Dec 16 14:03:14 foo owncast[26593]: time="2020-12-16T14:03:14+01:00" level=info msg="Incoming RTMP connected."
Dec 16 14:03:14 foo owncast[26593]: time="2020-12-16T14:03:14+01:00" level=trace msg="Video transcoder started with 1 stream variants."
Dec 16 14:03:14 foo owncast[26593]: time="2020-12-16T14:03:14+01:00" level=trace msg="[Type AMF0 Time 0 Len 405 Data [\"@setDataFrame\",\"onMetaData\",{\"duration\":0,\"fileSize\":0,\"width\":1280,\"height\":720,\"videocodecid\":7,\"videodatarate\":5000,\"framerate\":30,\"audiocodecid\":10,\"audiodatarate\":160,\"audiosamplerate\":48000,\"audiosamplesize\":16,\"audiochannels\":2,\"stereo\":true,\"2.1\":false,\"3.1\":false,\"4.0\":false,\"4.1\":false,\"5.1\":false,\"7.1\":false,\"encoder\":\"obs-output module (libobs version 26.0.2-2)\"}] Header ]\n"
Dec 16 14:03:34 foo owncast[26593]: time="2020-12-16T14:03:34+01:00" level=error msg="Unable to generate thumbnail: exit status 139"
Dec 16 14:03:54 foo owncast[26593]: time="2020-12-16T14:03:54+01:00" level=error msg="Unable to generate thumbnail: exit status 139"
Dec 16 14:04:04 foo owncast[26593]: time="2020-12-16T14:04:04+01:00" level=error msg="The CPU utilization of 80% can cause issues with video generation and delivery. Please visit the documentation at http://owncast.online/docs/troubleshooting/ to help troubleshoot this issue."
Dec 16 14:04:14 foo owncast[26593]: time="2020-12-16T14:04:14+01:00" level=trace msg="Deleting 2 old files from hls for video variant 0"
Dec 16 14:04:14 foo owncast[26593]: time="2020-12-16T14:04:14+01:00" level=error msg="Unable to generate thumbnail: exit status 139"
Dec 16 14:04:34 foo owncast[26593]: time="2020-12-16T14:04:34+01:00" level=error msg="Unable to generate thumbnail: exit status 139"
Dec 16 14:04:54 foo owncast[26593]: time="2020-12-16T14:04:54+01:00" level=error msg="Unable to generate thumbnail: exit status 139"
Dec 16 14:05:04 foo owncast[26593]: time="2020-12-16T14:05:04+01:00" level=trace msg="Deleting 14 old files from webroot/hls for video variant 0"
Dec 16 14:05:14 foo owncast[26593]: time="2020-12-16T14:05:14+01:00" level=trace msg="Deleting 15 old files from hls for video variant 0"
Dec 16 14:05:14 foo owncast[26593]: time="2020-12-16T14:05:14+01:00" level=error msg="Unable to generate thumbnail: exit status 139"
Dec 16 14:05:34 foo owncast[26593]: time="2020-12-16T14:05:34+01:00" level=error msg="Unable to generate thumbnail: exit status 139"
Dec 16 14:05:54 foo owncast[26593]: time="2020-12-16T14:05:54+01:00" level=error msg="Unable to generate thumbnail: exit status 139"
Dec 16 14:06:04 foo owncast[26593]: time="2020-12-16T14:06:04+01:00" level=trace msg="Deleting 15 old files from webroot/hls for video variant 0"
Dec 16 14:06:14 foo owncast[26593]: time="2020-12-16T14:06:14+01:00" level=trace msg="Deleting 15 old files from hls for video variant 0"
Dec 16 14:06:14 foo owncast[26593]: time="2020-12-16T14:06:14+01:00" level=error msg="Unable to generate thumbnail: exit status 139"
Dec 16 14:06:34 foo owncast[26593]: time="2020-12-16T14:06:34+01:00" level=error msg="Unable to generate thumbnail: exit status 139"
```

**Comment by gabek** [comment] 2020-12-16 16:41
I haven't seen that before!

Some questions to help track this down:

- Is everything else working, aside from thumbnail generation?
- It looks like you're running it as a system service, does it run the same just firing it from a shell?
- What version of ffmpeg are you using?
- Could you share your config file?

**Comment by SkYNewZ** [comment] 2020-12-16 17:35
- Everything else works as expected. And I must say it's really cool!
- Yes. I tried locally about 30 minutes before to discover the project: I launched owncast with `./owncast` and the same configuration file (except bitrate settings). Same OBS software, same YouTube downloaded video.
- `ffmpeg` version (installed alongside with `owncast` with your installation script):
```
quentin@vps689846:~/owncast$ ./ffmpeg -version
ffmpeg version 4.3.1-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2020 the FFmpeg developers
built with gcc 8 (Debian 8.3.0-6)
configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gmp --enable-libgme --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libdav1d --enable-libxvid --enable-libzvbi --enable-libzimg
libavutil      56. 51.100 / 56. 51.100
libavcodec     58. 91.100 / 58. 91.100
libavformat    58. 45.100 / 58. 45.100
libavdevice    58. 10.100 / 58. 10.100
libavfilter     7. 85.100 /  7. 85.100
libswscale      5.  7.100 /  5.  7.100
libswresample   3.  7.100 /  3.  7.100
libpostproc    55.  7.100 / 55.  7.100
```
- config file:
```
quentin@vps689846:~/owncast$ cat config.yaml 
# See https://owncast.online/docs/configuration/ for more details

webServerPort: 8081
instanceDetails:
  name: SkYNewZ
  title: SkYNewZ Owncast server
  summary: "Playing, coding and so on."

  logo: /img/logo.svg

  tags:
    - software
    - streaming
    - games

  nsfw: false

  # https://owncast.online/docs/configuration/#external-links
  # for full list of supported social links.  All optional.
  socialHandles:
    - platform: github
      url: http://github.com/SkYNewZ
    - platform: twitter
      url: https://twitter.com/skynewz_
    - platform: linkedin
      url: https://www.linkedin.com/in/skynewz/
    - platform: mastodon
      url: https://mstdn.social/@skynewz

videoSettings:
  # Change this value and keep it secure.  Treat it like a password to your live stream.
  streamingKey: <REDACTED>

  streamQualities:
    - high:
      videoBitrate: 8000
      encoderPreset: superfast
      audioPassthrough: true

# Set to true if you don't want the service checking for future releases.
disableUpgradeChecks: true

files:
  maxNumberInPlaylist: 2

# Off by default.  You can optionally list yourself in the Owncast directory.
# Make sure your instanceURL is the public URL to your Owncast instance.
yp:
  enabled: false
  instanceURL: https://stream.skynewz.dev
```

With a quick look on the code, because you run [`ffmpeg` as a subprocess](https://github.com/owncast/owncast/blob/2e1f8d29b5fbc97a91b4219458982d234e01bc0a/core/ffmpeg/thumbnailGenerator.go#L96), it's easy to deduce that ffmpeg exit with `status code 139`, but this does not seems to be a standard status code 😟.

Good luck !

**Comment by gabek** [comment] 2020-12-16 17:50
Yeah, I did the same research, to see if I could track down what 139 was, with no luck.

What it's doing is taking the most recently generated HLS segment and building a thumbnail from that.  Would you be able to provide a `.ts` file from your `webroot/hls` directory while it's running?  I'd love to see what it generates and try to manually run the 

The only thing that stands out is the bitrate of 8000 being quite high.  While I can't think why that can't be handled, it's the only thing really unique about your setup.

**Comment by SkYNewZ** [comment] 2020-12-16 18:06
I currently trying to debug the program with breakpoint on the goroutine **but**:
- on my laptop (macOS) which is not the same computer used for testing nor production server
- `owncast` from source code at tag `v0.0.3`
- same config file
- ffmpeg from system `ffmpeg version 4.3.1 Copyright (c) 2000-2020 the FFmpeg developers built with Apple clang version 12.0.0 (clang-1200.0.32.27)`

The thumbnail generator never fails 🤦🏻‍♂️…

For the bitrate, I didn't understand everything in this area, I stupidly followed https://support.video.ibm.com/hc/en-us/articles/207852117-Internet-connection-and-recommended-encoding-settings searching for `1920x1080`.

There is my `webroot/hls` folder: https://drive.google.com/file/d/11TimanP7sVbuYmsIfFdAtba4EMBJgFZD/view

**Comment by SkYNewZ** [comment] 2020-12-16 18:10
You have the server logs in live 😅

**Comment by gabek** [comment] 2020-12-17 08:41
Just like you, I'm unable to reproduce it.  When manually running the command to create a thumbnail against your files it works just fine.  Just to make sure I grabbed the same version of ffmpeg.

Could you try running this on the server you're having problems with so we can see what else ffmpeg has to say?

```
ffmpeg -y -threads 1 -t 1 -i hls/0/stream-<something>.ts -f image2 -vframes 1 thumbnail.jpg
```

Pick any .ts file.

**Comment by SkYNewZ** [comment] 2020-12-18 09:14
```
quentin@vps689846:~/owncast$ ./ffmpeg -y -threads 1 -t 1 -i hls/0/stream-4NWIOj1MR1608282762.ts -f image2 -vframes 1 thumbnail.jpg
ffmpeg version 4.3.1-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gmp --enable-libgme --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libdav1d --enable-libxvid --enable-libzvbi --enable-libzimg
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Segmentation fault
quentin@vps689846:~/owncast$ echo $?
139
```

Maybe a server issue ? haha

**Comment by gabek** [comment] 2020-12-18 09:24
Doh!  That's not helpful.  But does seem to point that particular build of ffmpeg (or one of the libraries that are included in that static build) and your machine being unhappy.  Do you think you could install ffmpeg using your system's software packages?

**Comment by gabek** [comment] 2020-12-18 09:25
Or try grabbing the most recent git master builds from here?  https://johnvansickle.com/ffmpeg/

**Comment by SkYNewZ** [comment] 2020-12-18 10:00
According to https://askubuntu.com/questions/432542/is-ffmpeg-missing-from-the-official-repositories-in-14-04, I can't install `ffmpeg` from system's software packages. So I'm using the `git master: built on 20201128`.

```
quentin@vps689846:~/owncast$ ./ffmpeg-git-20201128-amd64-static -y -threads 1 -t 1 -i hls/0/stream-M5qQ5jJMg1608285500.ts -f image2 -vframes 1 thumbnail.jpg
ffmpeg version N-55112-g7eb9cf593e-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gmp --enable-libgme --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libdav1d --enable-libxvid --enable-libzvbi --enable-libzimg
  libavutil      56. 61.100 / 56. 61.100
  libavcodec     58.114.100 / 58.114.100
  libavformat    58. 64.100 / 58. 64.100
  libavdevice    58. 11.103 / 58. 11.103
  libavfilter     7. 91.100 /  7. 91.100
  libswscale      5.  8.100 /  5.  8.100
  libswresample   3.  8.100 /  3.  8.100
  libpostproc    55.  8.100 / 55.  8.100
Segmentation fault
```

**Comment by SkYNewZ** [comment] 2020-12-18 10:17
It seems to be my system fault

**Comment by gabek** [comment] 2020-12-28 02:17
@SkYNewZ Has this been resolved?  Is there anything on the Owncast end that needs to be looked at?

**Comment by SkYNewZ** [comment] 2020-12-28 13:39
Honestly, I don't know. Yes I still have the bug but none of us know where it comes from and I don't have the bug anywhere else...

**Comment by gabek** [comment] 2021-01-20 02:35
Going to close this unless there's anything actionable that can be looked into.

**Closed by gabek** 2021-01-20 02:35 UTC
