### ISSUE TITLE
[Feature Request] Support P2P Streams for better performance

### ISSUE THREAD

**Issue by asandikci** [owncast/owncast#3517] opened 2024-01-12 11:36 UTC
Support Peer to peer streams for better performance. This also provides that not dependent on cloudflare. Streaming server (owncast) will have less load and more people could be handled with this feature.

This feature should be toggleable in the admins settings

For implementation and examples, you can see PeerTube project

**Comment by gabek** [comment] 2024-01-15 04:15
Duplicate of #112.

**Closed as not planned by gabek** 2024-01-15 04:15 UTC
