### ISSUE TITLE
Make all links open in a new tab by default

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2160] opened 2022-10-02 21:08 UTC
### Share your bug report, feature request, or comment.

We're doing that in the old UI, but we need to add this to webv2 as well. I believe it's just an additional tag in the html head.

**Comment by Kundan1804** [comment] 2022-10-03 19:56
Hey @gabek  I am a frond end developer and would love to contribute in this issue an you please assign this to me.

**Comment by gabek** [comment] 2022-10-03 19:58
Absolutely, thank you!

**Comment by Kundan1804** [comment] 2022-10-04 13:44
Hey @gabek! thank you for assigning this issue to me. I cloned the repository but i am unable to run the project, can you help me out please

**Comment by gabek** [comment] 2022-10-04 15:44
Sure. What specific problem are you trying to solve? Did you get a chance to follow the instructions at https://owncast.online/development/ ?

<blockquote><img src="/images/owncast-logo-1000x1000.png" width="48" align="right"><div><img src="/favicon.png" height="14"> Owncast</div><div><strong><a href="/development/">How to work on Owncast</a></strong></div><div>The technical details for those wishing to take part in Owncast development.</div></blockquote>

**Comment by Kundan1804** [comment] 2022-10-04 17:08
i Followed to instruction launched the web app and i am getting this error-

"Owncast cannot launch. Please make sure the Owncast server is running. SyntaxError: Unexpected token '<' , "<!Doctype "..... is not valid Jason"

**Comment by gabek** [comment] 2022-10-04 17:09
Is the Owncast server running?

**Comment by Kundan1804** [comment] 2022-10-04 18:45
How do i check it?

**Comment by gabek** [comment] 2022-10-04 18:57
Did you setup the backend for the frontend to talk to? If you didn't, or if it's not running then the frontend can't do anything and will throw the error "Please make sure the Owncast server is running." It sounds like you might not have done this.

Make sure Owncast is running on your local machine. There's details about how to do this in the development document: https://owncast.online/development

<blockquote><img src="/images/owncast-logo-1000x1000.png" width="48" align="right"><div><img src="/favicon.png" height="14"> Owncast</div><div><strong><a href="/development/">How to work on Owncast</a></strong></div><div>The technical details for those wishing to take part in Owncast development.</div></blockquote>

**Comment by Kundan1804** [comment] 2022-10-04 20:59
I am getting this error while trying to run the main.go file

"Unable to determine path to ffmpeg. Please specify it in the admin or place a copy in Owncast Directory".
I have downloaded ffmpeg can you tell me what to do next.

**Comment by gabek** [comment] 2022-10-04 22:24
Is the actual binary of ffmpeg in the same directory of Owncast? Not a zip file or anything?

**Comment by Kundan1804** [comment] 2022-10-05 11:11
yes it is the actual binary file. I have added it to system environment path and even copied the file to owncast cloned repository location.

**Comment by gabek** [comment] 2022-10-05 15:27
Is the binary called `ffmpeg` not something else for some reason?

**Comment by Kundan1804** [comment] 2022-10-05 17:31
no its exactly "ffmpeg". Is there a specific sub folder where i should copy it?

**Comment by gabek** [comment] 2022-10-05 17:39
I'm admittedly clueless on what is happening there. It's a pretty straightforward setup that I haven't heard of anybody else having issues with. You just make sure ffmpeg is available and that's it.

The [installer](https://owncast.online/quickstart/installer/) does the same thing, it simply puts a copy of ffmpeg in the same directory of Owncast.

**Comment by Kundan1804** [comment] 2022-10-05 20:29
Ok give me some time Ill work a way around it

**Comment by gabek** [comment] 2022-10-05 21:45
If it helps at all, you don't need to have a live video stream to work on this particular issue since it doesn't rely on chat or the video player.

**Comment by gabek** [comment] 2022-10-10 21:55
We should be able to add the attribute to `no-link-referrer.ts`.

**Comment by gabek** [comment] 2022-10-19 05:39
Here you go, you can just add this one tag:

https://dev.to/jyotishman/html-tip-automatically-open-all-links-in-new-tab-in-html-19ok

<blockquote><img src="https://dev.to/social_previews/article/740640.png" width="48" align="right"><div><img src="https://res.cloudinary.com/practicaldev/image/fetch/s--lrmEcD2H--/c_limit,f_png,fl_progressive,q_80,w_128/https://practicaldev-herokuapp-com.freetls.fastly.net/assets/devlogo-pwa-512.png" height="14"> DEV Community 👩‍💻👨‍💻</div><div><strong><a href="https://dev.to/jyotishman/html-tip-automatically-open-all-links-in-new-tab-in-html-19ok">HTML Tip: Automatically open all links in new tab in HTML</a></strong></div><div>Did you get tired of manually adding target="_blank" in all the  tags in your HTML webpage? or Have...</div></blockquote>

**Comment by Kundan1804** [comment] 2022-10-20 08:17
yeah i know the tag but the problem is that particular tag is to be added in the main html file of the project which contains all the components of the project, and i am unable to find that root html file.

**Comment by Kundan1804** [comment] 2022-10-20 10:33
I am sorry @gabek i tired my best but i am unable to solve this issue, you may please unassign me.

**Closed as completed** 2022-10-21 03:17 UTC
Labels: good first issue, Web frontend
