### ISSUE TITLE
Stream Ending Screen

### ISSUE THREAD

**Issue by NullRien** [owncast/owncast#2046] opened 2022-08-18 01:14 UTC
I dont know how to change the stream ending screen but if there was a easy way via the admin panel i think that would be a neat feature.

**Comment by gabek** [comment] 2022-08-18 01:29
Take a look through issues and discussions for previous discussion about this.

**Comment by NullRien** [comment] 2022-08-18 02:04
> Take a look through issues and discussions for previous discussion about this.

i did look for it but i could not find it, if you could link it id appreciate it.

**Comment by gabek** [comment] 2022-08-18 05:34
Sorry about that, I wasn't in front of a computer when I responded earlier. Closing this as a duplicate of the discussion at #1965.

**Closed as not planned by gabek** 2022-08-18 05:34 UTC
