### ISSUE TITLE
Firefox: URL adds a mysterious "#"

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#3240] opened 2023-08-06 21:08 UTC
### Share your bug report, feature request, or comment.

This doesn't happen on Chromium-based browsers. It doesn't seem to be impacting anything, but it's kind of annoying because it looks like it's there on purpose and makes you wonder why.

![image](https://github.com/owncast/owncast/assets/414923/899289df-ebad-4ce2-9e0d-43c432bd9167)

**Comment by AMalfez** [comment] 2023-09-06 10:23
Hi
I'm alfez mansuri new to open source.
I'm interested in working on it.
Could you assign it to me?

**Comment by gabek** [comment] 2023-09-06 17:10
Absolutely, thank you @AMalfez!

**Comment by AMalfez** [comment] 2023-09-07 13:35
Hi
is this problem arrise only on some urls or any url?

**Comment by gabek** [comment] 2023-09-07 18:53
On every Owncast server it seems.

For example: Visit https://watch.owncast.online and the browser bar changes to:

![image](https://github.com/owncast/owncast/assets/414923/7db8d00e-e190-4575-8e6f-f4bed594a540)

<blockquote><img src="https://watch.owncast.online/thumbnail.jpg" width="48" align="right"><div><img src="/img/favicon/favicon-16x16.png" height="14"> Owncast TV</div><div><strong><a href="https://watch.owncast.online/">Owncast TV</a></strong></div><div>An example stream where you can learn more about Owncast, as well as other projects we want to share.</div></blockquote>

**Comment by AMalfez** [comment] 2023-09-08 04:17
hi
![image](https://github.com/owncast/owncast/assets/95576731/8d19789b-1b6a-4bfb-a929-c181f7e5a268)
as you can see in the image, is there a file missing?

**Comment by gabek** [comment] 2023-09-08 06:08
Owncast doesn't natively run on Windows. Follow this document: 

https://github.com/owncast/owncast/blob/develop/contrib/owncast_for_windows.md

**Comment by gabek** [comment] 2023-09-18 23:33
@AMalfez Have you been able to track anything down?

**Comment by AMalfez** [comment] 2023-09-20 06:48
Sorry
I was unable to do anything due to some other engagements.
Will try from now on...

**Comment by AMalfez** [comment] 2023-09-20 07:09
can you tell me which file/files are handling routing in the app?

**Comment by gabek** [comment] 2023-09-20 15:18
It depends on what you mean.

The Owncast frontend web app (where this issue occurs) is only a single page, so there is no routing there.
The admin, however, uses filesystem-based routing in the web application.
The backend server routing is configured in `router.go`.

**Comment by AMalfez** [comment] 2023-09-23 14:25
after lot of try, i couldn't find any fix :(
Only thing i can find is this article:
https://support.mozilla.org/en-US/questions/957252
Could you help me find relevant files for it?

<blockquote><img src="https://assets-prod.sumo.prod.webservices.mozgcp.net/static/favicon.03d97697df808c0e.ico" width="48" align="right"><div><strong><a href="https://support.mozilla.org/en-US/questions/957252">URL ends with # | Firefox Support Forum | Mozilla Support</a></strong></div></blockquote>

**Comment by gabek** [comment] 2023-09-23 17:19
The web source files can be found in the `web` directory.

**Comment by unclebinary1001** [comment] 2023-10-05 05:28
Hi, can I look into this if no one else is?

**Comment by gabek** [comment] 2023-10-05 06:11
@unclebinary1001 Sure! Nothing has been found so far, and it looks like it's kind of stalled, so go for it!

**Comment by pjbollinger** [comment] 2023-10-08 23:00
Any qualms with me picking this up? It's been a few days since assignment, but I didn't want to step on toes. I use Firefox as my main browser and it's been annoying me as I set up my instance. 😬 

This was trickier than expected, but the root of the problem is Firefox will set `#` in the URL bar when `window.location.hash` is set to _any_ string, even a blank string. So, [the code on line 378 of `ClientConfigStore.tsx`](https://github.com/owncast/owncast/blob/bbbaca4123c599152b6d2243e67a4c1688a7839d/web/components/stores/ClientConfigStore.tsx#L378) is unknowingly modifying the URL. I'm thinking through alternatives but the morale of the story is, don't mutate base data if you just want to copy values. 😅 

Sample of Firefox JavaScript console session that demonstrates the issue:
```javascript
>> window.location.href
"https://github.com/owncast/owncast/issues/3240"

>> const setBlankHash = () => { window.location.hash = ''; };
undefined

>> window.location.hash
""

>> window.location.href
"https://github.com/owncast/owncast/issues/3240"

>> setBlankHash()
undefined

>> // My browser just jumped to the top of the page
undefined

>> window.location.hash
""

>> window.location.href
"https://github.com/owncast/owncast/issues/3240#" 
```

Not sure if this is a bug or feature for Firefox, but TIL. 😆

**Comment by gabek** [comment] 2023-10-08 23:14
Oh awesome! Thanks for digging into it. It doesn't look like there's been any progress, and you've tracked it down, so hopefully nobody will mind if you grab it. Thanks again for going down this rabbit hole!

**Closed as completed** 2023-10-09 01:58 UTC
Labels: bug, good first issue, Web frontend, hacktoberfest
