### ISSUE TITLE
Mobile UI - Chat message entry not visible in portrait mode, only landscape mode

### ISSUE THREAD

**Issue by jprjr** [owncast/owncast#2005] opened 2022-07-17 19:41 UTC
This is an issue I found in v0.0.12 - when a user pulls up the site on a mobile browser, the message entry isn't visible in portrait mode. It does appear if switching to landscape mode.

Tested on Chrome for Android and Firefox for Android, both have the same issue.

**Comment by gabek** [comment] 2022-07-17 21:21
Closing as a dupe of #1933. This will be resolved in the rewrite of the web stuff, sorry about that.

**Closed as not planned by gabek** 2022-07-17 21:21 UTC
