### ISSUE TITLE
0.0.10 binary won't run on macOS 10.14.6

### ISSUE THREAD

**Issue by zmip** [owncast/owncast#1705] opened 2022-01-27 09:25 UTC
I downloaded the latest release for macOS to my (local) development machine, and I've configured my local webserver (Apache) correctly. The webroot is correctly loading (I see the HTML and js files getting loaded in a webbrowser), but I can't get the binary started: panic: `invalid argument` at `setSystemConcurrentConnectionLimit`:

```
$ ./owncast
INFO[2022-01-27T10:17:04+01:00] Owncast v0.0.10-macOS-64bit (737dbf9b1a444b0b7d415da819c16d74d3d7812e) 
INFO[2022-01-27T10:17:04+01:00] Video transcoder started using x264 with 1 stream variants. 
panic: invalid argument

goroutine 1 [running]:
github.com/owncast/owncast/core/chat.setSystemConcurrentConnectionLimit(0x5999998000000000)
	/go/src/github.com/owncast/owncast/core/chat/concurrentConnections.go:21 +0x19d
github.com/owncast/owncast/core/chat.NewChat(0x515a180)
	/go/src/github.com/owncast/owncast/core/chat/server.go:46 +0x34
github.com/owncast/owncast/core/chat.Start(0x4e998c0, 0xc0000b6b10, 0x5753190)
	/go/src/github.com/owncast/owncast/core/chat/chat.go:20 +0x44
github.com/owncast/owncast/core.Start(0x4b9e6fc, 0x7)
	/go/src/github.com/owncast/owncast/core/core.go:68 +0x262
main.main()
	/go/src/github.com/owncast/owncast/main.go:124 +0x631
```
I'm not sure what to try next. Building from source?

**Comment by gabek** [comment] 2022-01-27 17:40
I'm certainly able to run from source, so maybe give that a shot, but you're also running a much older version of macOS than I have access to.  I'll see if I can reproduce and figure it out with my setup, though.

But I'm a little confused how Owncast is serving the web content if you can't start the Owncast binary.

**Comment by gabek** [comment] 2022-01-28 00:13
For the record I just tested:

![image](https://user-images.githubusercontent.com/414923/151464451-4094181a-33e3-4b57-ab2e-73fed174aa43.png)

**Comment by zmip** [comment] 2022-01-28 06:02
Thanks @gabek, you're right, this is my development machine, and I currently can't upgrade because I'm in the middle of a few projects. The reason the files get served is because Apache is running on this machine too. And that probably explains one of the problems: port 8080 is in use. Is it possible to start Owncast from the command line on different ports (are you using 8080 for the stream and chat websockets?)

**Comment by gabek** [comment] 2022-01-28 06:08
I guess I should clarify, Owncast is its own webserver, so if you have Apache serving files on behalf of Owncast something isn't right there.  Port 8080 is the default web server port for all of Owncast, but you can change it.  Run `owncast` with `--help` to see a list of flags.

As for the macOS thing, unless other people report the same issue it's probably not worth trying to support old versions of macOS. To be fair I doubt many people run it on macOS at all.  I'll go ahead and close this issue, since I don't believe there's anything actionable.

But like always, you could just run the source and comment out anything that's incompatible with the old version of macOS.

**Closed as completed by gabek** 2022-01-28 06:08 UTC
