### ISSUE TITLE
Viewer count and live time not properly shown on embed with 0.1.1

### ISSUE THREAD

**Issue by JoanLP** [owncast/owncast#3266] opened 2023-08-19 05:44 UTC
### Share your bug report, feature request, or comment.

Hello,

I love the new design on 0.1.1. However, the viewer and live time is not showing properly on embed especially on mobile. It is cropped off.

A great example to see this is on your own embed example here:
https://owncast.online/docs/embed/

I think the viewer count live stream timer need a better look. I liked the way it was on the older versions.

Thank you.

**Comment by gabek** [comment] 2023-08-19 05:47
Duplicate of #3210.

**Closed as not planned by gabek** 2023-08-19 05:47 UTC
