### ISSUE TITLE
'Hiding Message' in admin panel is not working

### ISSUE THREAD

**Issue by H3J0** [owncast/owncast#2066] opened 2022-08-28 18:59 UTC
### Share your bug report, feature request, or comment.

<img width="951" alt="image" src="https://user-images.githubusercontent.com/109244700/187090268-34e1aab5-7b84-4777-9456-ab44e58852ad.png">

As the title states, does this feature not work. Le fractal was the first one to notice it. We have tested it on 2 instances of the 0.0.12 Owncast server _(Owncast v0.0.12-linux-64bit). 

Most likely not relevant, but we are both using nginx (1.18 and 1.20).

Mods can still hide messages.

The browser dev tool informs us, that an api endpoint isn't available, if I understand it correctly:
` XHRPOSThttps://hejo.org/api/admin/chat/updatemessagevisibility [HTTP/1.1 404 Not Found 34ms]`

Let me know if someone needs more information.

**Comment by gabek** [comment] 2022-08-28 19:03
Duplicate of #2020.

**Closed as not planned by gabek** 2022-08-28 19:03 UTC
