### ISSUE TITLE
VIdeo configuration UI: "lowest" cpu usage displayed as "n/a"

### ISSUE THREAD

**Issue by taintedcypher** [owncast/owncast#2900] opened 2023-04-03 21:27 UTC
### Share your bug report, feature request, or comment.

When I configure a stream variant using the "lowest" cpu usage preset, the CPU usage is displayed as "n/a" in the stream variant list.
![image](https://user-images.githubusercontent.com/119351153/229630708-19302648-80f2-48a2-b874-369b922103bb.png)

Tested on Firefox 111 (Linux), Ungoogled Chromium 111 (Linux)

**Comment by gabek** [comment] 2023-04-03 21:30
Sorry about that, this was filed and not triaged so it got lost in the mix. Closing as a duplicate of #2800.

**Closed as not planned by gabek** 2023-04-03 21:30 UTC
