### ISSUE TITLE
Multiple auth registration message should not display as fatal error

### ISSUE THREAD

**Issue by Troyjan20072001** [owncast/owncast#3103] opened 2023-06-25 15:05 UTC
### Share your bug report, feature request, or comment.

There was an unexpected error. It would be appreciated if you would report this so it can be fixed in the future.

You may optionally retry, however functionality might not work as expected.
Error: P.includes is not a function
Component: AuthModal

Error
Could not register auth request. One may already be pending. Try again later. 

which last code was 22 hours ago

**Comment by gabek** [comment] 2023-06-25 15:22
Thanks for filing this. It shouldn't be displayed as an error, since this is a valid state if you submit two auth requests.

> Could not register auth request. One may already be pending. Try again later.

That means you requested to start auth once, and then did it again without finishing the first one. It won't let you do that until the first one times out.

Additionally it looks like there's a bug, since this message is shown as an error:

> Error: P.includes is not a function

**Comment by Troyjan20072001** [comment] 2023-06-25 15:41
we figured it out. one of my Add-Ons for Firefox was causing the issue. Thank you for getting back to me

**Comment by gabek** [comment] 2023-06-27 23:31
I thought there might be a bigger issue here with how the error is displayed, but I wasn't able to reproduce this by registering for auth twice in a row. So maybe it was entirely the Firebox add-on that caused the issue. Closing.

**Closed as not planned by gabek** 2023-06-27 23:31 UTC
Labels: bug, Web frontend
