### ISSUE TITLE
don't spam the screenreader for how much the channel is live.

### ISSUE THREAD

**Issue by patricus3** [owncast/owncast#3862] opened 2024-07-31 16:28 UTC
hello.
that's the only issue with owncast.
when I enter any stream, my screenreader inform me every few seconds for how much the instance is live for.

**Comment by gabek** [comment] 2024-07-31 17:01
Closing as a duplicate of #3334. It should be resolved in v0.1.2. Use that thread if there are issues with that change.

**Closed as not planned by gabek** 2024-07-31 17:01 UTC
