### ISSUE TITLE
Fix incompatible type in ClientTable

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#3339] opened 2023-10-05 19:48 UTC
### Share your bug report, feature request, or comment.

```
./components/admin/ClientTable.tsx:44:13
Type error: Type 'Key' is not assignable to type 'string | number | readonly string[]'.
  Type 'bigint' is not assignable to type 'string | number | readonly string[]'.

  42 |           <Input
  43 |             placeholder="Search display names..."
> 44 |             value={selectedKeys[0]}
     |             ^
  45 |             onChange={e => {
  46 |               setSelectedKeys(e.target.value ? [e.target.value] : []);
  47 |               confirm({ closeDropdown: false });
```

**Comment by Dhoni77** [comment] 2023-10-06 04:17
Hi @gabek
I am not able to reproduce this type error in local.

Attachment:

![type error](https://github.com/owncast/owncast/assets/53973174/c9069976-b09e-4493-9299-438537570636)

**Comment by vishal-sharma-369** [comment] 2023-10-06 04:47
I have solved this issue in my local environment. Please assign this issue to me.

**Closed as completed** 2023-10-07 20:14 UTC
Labels: good first issue, admin, hacktoberfest
