### ISSUE TITLE
add support for Tencent Cloud

### ISSUE THREAD

**Issue by ishelo** [owncast/owncast#862] opened 2021-03-27 15:02 UTC
save video to the server storage ,or add tencent bucket [https://cloud.tencent.com/document/product/436](url)

**Comment by jeyemwey** [comment] 2021-03-27 16:01
Hi, according to [their international homepage](https://intl.cloud.tencent.com/product/cos), Tencent Object Storage is compatible with the S3 APIs. Can you check if putting your credentials into Owncast works or what the issue is?

**Comment by gabek** [comment] 2021-03-31 01:32
Closing this as any S3 provider should be supported, but feel free to re-open if there are issues.

**Closed by gabek** 2021-03-31 01:32 UTC
