### ISSUE TITLE
[Crash] fatal error: concurrent map writes

### ISSUE THREAD

**Issue by jprjr** [owncast/owncast#3543] opened 2024-02-08 19:46 UTC
### Share your bug report, feature request, or comment.

Hi there - I recently (finally) upgraded to 0.1.2 and started getting the occasional crash.

I'm using s3 storage with 2 variant streams, and I think it has something to do with that, I'm attaching my systemd logs from the most recent crash. The error seems to be from https://github.com/owncast/owncast/blob/v0.1.2/core/storageproviders/s3Storage.go#L134

[concurrent map writes.txt](https://github.com/owncast/owncast/files/14213961/concurrent.map.writes.txt)

**Comment by gabek** [comment] 2024-02-08 21:16
Duplicate of #3440.

**Closed as not planned by gabek** 2024-02-08 21:16 UTC
