### ISSUE TITLE
Copying stream key without revealing it only copies asterisks (when using clipboard manager?)

### ISSUE THREAD

**Issue by Roboron3042** [owncast/owncast#3460] opened 2023-12-02 17:32 UTC
### Share your bug report, feature request, or comment.

Just installed version 0.1.2 and when configuring OBS I copied the streaming key from the /admin/config/server/ owncast page, but without revealing it first. But only asterisks were copied, not the actual password. I had to click the button to reveal the password, then click the copy button again to copy the actual password.

**Comment by takuabonn** [comment] 2023-12-03 02:00
hi @gabek @Roboron3042 
I want to work in this issue. will u assign it to me?

**Comment by gabek** [comment] 2023-12-03 02:02
Of course, thanks so much!

**Comment by takuabonn** [comment] 2023-12-03 02:07
hi @gabek 
thank you.
I will do my best!

**Comment by takuabonn** [comment] 2023-12-04 00:56
hi @gabek 
I have two question.

hwo to access database?
how to reset streamkeys?

**Comment by gabek** [comment] 2023-12-04 01:50
This asterisks issue is frontend only, so you won't need to make any changes to the database.

If you need to reset your stream key or admin password check out the documentation: https://owncast.online/troubleshoot/change-streamkey/

You could also just delete the `data` directory if you're just developing locally and start over.

<blockquote><img src="/images/owncast-logo-1000x1000.png" width="48" align="right"><div><img src="https://owncast.online/favicon.png" height="14"> Owncast</div><div><strong><a href="/troubleshoot/change-streamkey/">Change your streaming key & admin password</a></strong></div><div>Change the key you use for streaming and logging into your admin.</div></blockquote>

**Comment by takuabonn** [comment] 2023-12-04 05:18
hi @gabek @Roboron3042 

Thank you for answering.

I clicked copy button without click red line button.
correct copied stream key(abc123) but no astarisk.
Is there a wrong way to reproduce it?

![owncast1](https://github.com/owncast/owncast/assets/70795978/336c63d6-8f22-46fc-a4bb-301519f5e263)

**Comment by taintedcypher** [comment] 2023-12-04 20:21
This might be useful: there was a similar issue earlier this year https://github.com/owncast/owncast/issues/2897

**Comment by takuabonn** [comment] 2023-12-04 23:06
hi @taintedcypher 

Thank you!
Does this mean that the problem occurs on a specific server other than the local server?
I can't reproduce it locally.

**Comment by taintedcypher** [comment] 2023-12-05 15:13
> hi @taintedcypher
> 
> Thank you! Does this mean that the problem occurs on a specific server other than the local server? I can't reproduce it locally.

Hi! Sorry I haven't tried 0.1.2 yet!
The issue I referenced had been fixed at the time, and I just checked on my 0.1.1 server: the copy function functions properly.
I just wanted to make sure whoever takes on this issue can look through the old issue if it's any help!

**Comment by gabek** [comment] 2023-12-05 17:43
I just tested it on a nightly build, and it works fine for me too. @Roboron3042 can you provide any details? It seems like none of us can reproduce your issue.

**Comment by Roboron3042** [comment] 2023-12-10 20:45
- Owncast v0.1.2
- Firefox 120.0.1
- Owncast server on another machine, but on my same LAN.
- Accessing the admin panel through its local IP and port: http://192.168.0.42:8081
- From Home I click on "Streaming Keys: View" which navigates to http://192.168.0.42:8081/admin/config/server/
- Then I click "Stream Keys" tab and the copy button inside it.
- Pasting the copied content only paste asterisks.

**Comment by taintedcypher** [comment] 2023-12-12 18:07
Ahah, I'm about to add to the confusion.
I updated to 0.1.2 (docker) and figured I would try to reproduce this If I could.

For context, I use a clipboard history manager ("copyq", it keeps a history of everything I copy).

- In Firefox 120, I noticed that when I copy the stream key using the 'copy' button, two copy operations are made in succession: one copying asterisks, and then one copying the actual key. Without the clipboard history you wouldn't be able to tell, since the second copy operation overwrites the clipboard.
- In (Ungoogled) Chromium 119, there is only one copy operation, which copies the actual key straight away.

Maybe this helps shed some light on @Roboron3042's issue.

**Comment by mahmed2000** [comment] 2024-04-08 12:23
I see the problem(s). Reproduction requires access through the LAN address 192.168... over http (**not** https) and **not** localhost. 

All relevant to `web/components/admin/config/server/StreamKeys.tsx`:
1) The copyable attribute from andt implements all the needed functionality for copying. The extra copyText function is just a duplicate bandaid copy.
2) The copyable attribute sets the copy text to `showKeyMap[text] ? text : '**********'` which literally just tells it to copy asterisks if the key is hidden, otherwise copy the key.
3) Normally the copyText function would just overwrite it with the proper key when called by the onClick attribute.
4) However, it uses the `navigator.clipboard` API which relies on either localhost or HTTPS origins. http on a LAN address causes it to fail, and the first conditional copy stays set which is just a bunch of asterisks.

**Closed as completed** 2024-04-10 20:15 UTC
Labels: good first issue, admin
