### ISSUE TITLE
Chat input placeholder text showing up weird on mobile

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2991] opened 2023-05-06 19:29 UTC
I believe this to be specific to mobile. 

![image](https://user-images.githubusercontent.com/414923/236643211-096307f6-a655-438b-97d5-b51e6accba68.png)

**Comment by YadNash** [comment] 2023-05-07 09:18
Can you specify the problem

**Comment by gabek** [comment] 2023-05-07 16:07
If you look at the above screenshot you'll see how the chat input placeholder text is positioned incorrectly. There's a big green arrow pointing to it, the placeholder is barely visible but it's there.

**Comment by Gallantfarhan** [comment] 2023-05-08 12:32
is anybody working on this issue? if not you can assign me to this issue.

**Comment by gabek** [comment] 2023-05-08 15:29
I haven't started looking at it yet, so you're more than welcome to check it out. Thanks so much!

**Comment by Gallantfarhan** [comment] 2023-05-08 16:36
![Screenshot 2023-05-08 215848](https://user-images.githubusercontent.com/102584554/236878411-38671e47-275b-48e8-b91f-32cb056ce779.png)
working perfectly fine on my machine.

**Comment by gabek** [comment] 2023-05-08 16:38
Sorry about that, it's only an issue on mobile. I'll update the description. https://listen.batstationrad.io and https://watch.owncast.online are two servers you can see the issue with.

Here's another example. 

![image](https://user-images.githubusercontent.com/414923/236882122-88972d5a-5565-4678-bb69-e48b1237969a.png)

**Comment by thisprojects** [comment] 2023-05-15 20:42
I can reproduce this using a real device (iPhone SE),  doesn't appear in simulator and looks ok on my samsung galaxy android. Weird. Something is forcing the text below the icons and its causing the containing box to overflow with scroll. 

Actually this also occurs on desktop safari - if you shrink the screen size down to mobile view.

**Comment by gabek** [comment] 2023-05-17 01:31
Hi @Gallantfarhan, are you still looking at this? Let me know if you have any questions!

**Comment by Gallantfarhan** [comment] 2023-05-18 11:42
I've been given the responsibility to fix a bug in the code that deals with correcting placeholder text. It's puzzling because everything seems to be working perfectly fine on my computer and Android device. I've spent quite some time trying to find the problem, but unfortunately, I haven't been successful. I believe it would be best to assign this task to someone else who might have a fresh perspective and be able to identify the issue.

**Closed as completed** 2023-05-18 21:08 UTC
Labels: bug, good first issue, Web frontend, chat, mobile
