### ISSUE TITLE
Page vertical spacing layout issues

### ISSUE THREAD

**Issue by gabek** [owncast/owncast#2668] opened 2023-02-02 20:52 UTC
When scrolling down the footer never stays in view when testing on an iPad using Safari.

https://user-images.githubusercontent.com/414923/216446788-45e6cfe0-ebba-4ff3-af00-63872f9941ef.MOV

**Comment by gabek** [comment] 2023-02-11 00:16
With the recent layout changes that were merged in the issues with iPad changed. Both portrait and landscape have different issues.

iPad portrait has a gap between the header and the offline message. It also has excessive vertical spacing between all the components.

![image](https://user-images.githubusercontent.com/414923/218225243-f988f255-02cd-4f8b-8483-24a4386a80f0.png)

iPad landscape cuts off the header at the top of the page.

![image](https://user-images.githubusercontent.com/414923/218225254-f90c610c-d8de-492e-ae7c-c6e794eed37f.png)

iPad landscape on chrome is a bit different

![image](https://user-images.githubusercontent.com/414923/218225680-06c3223d-2c98-417e-a4f0-9a762cc60719.png)

**Comment by gabek** [comment] 2023-02-12 02:49
I've automated some screenshots on different browsers and platforms to hopefully allow catching more of this. Right now it's only taking one set of screenshots per day, but at least it's something. https://owncast.online/components/?path=%2Fdocs%2Fowncast-screenshots-ipad-portrait-safari--online

<blockquote><div><strong><a href="https://owncast.online/components/?path=%2Fdocs%2Fowncast-screenshots-ipad-portrait-safari--online">Webpack App</a></strong></div></blockquote>

**Comment by gabek** [comment] 2023-02-18 20:08
@LBBO Sorry to bug you, but I was looking into this and the culprit for some of these spacing issues seem to be from the `placeholder` divs that were added previously. I tried removing them and it seems to help, but I'm curious if they're required for some case I'm not aware of, and if so, can they be hidden or be sizeless so they don't add these spaces?

**Comment by LBBO** [comment] 2023-02-18 20:21
Sorry, I've been a bit busy with exams and work lately.

The idea behind the placeholder divs that I added was to have a constant number of divs under the container at all times so I wouldn't have to have different layouts for when this is hidden or when that is hidden. My plan was to design the heights such that the actual components would get their desired height while the placeholders collapse into nothingness, but I guess something went wrong there.

With the CSS I wrote, removing the placeholders might throw off the grid, but I guess that could be fixed with `grid-area`s. However, I would assume that the actual issue here might be with the heights assigned to the grid rows.

I was planning on continuing work on the stories tomorrow or Monday. If you'd like, I could take a look at this as well.

**Comment by gabek** [comment] 2023-02-18 22:13
Ok! In that case I'll hold back, since you had a plan and know where to look and that makes more sense than me poking around and experimenting. Let me know if there's anything I can do to help!

**Comment by gabek** [comment] 2023-02-25 10:17
Just for completeness, it looks like desktops browsers of certain sizes have the same issue as seen in this comment:

https://github.com/owncast/owncast/issues/2731#issuecomment-1445042651

**Comment by gabek** [comment] 2023-02-27 20:44
> The idea behind the placeholder divs that I added was to have a constant number of divs under the container at all times so I wouldn't have to have different layouts for when this is hidden or when that is hidden. 

What would happen if we set the placeholder divs to `display: none`, do they still count and fulfill their role in keeping a constant number of divs in the container?

**Comment by gabek** [comment] 2023-03-09 19:36
Additional scenario. On mobile when there is no tab bar the page is unscrollable.  

![image](https://user-images.githubusercontent.com/414923/224134995-4dc233df-fcea-4f08-a9d4-c5a184499962.png)

**Comment by gabek** [comment] 2023-03-10 23:44
Since this is currently a major blocker I'm going to try the approach on making the placeholders `display: none;` and hope for the best.

**Comment by gabek** [comment] 2023-03-13 23:06
There's much larger issues here than the placeholders unfortunately. The placeholders can be hidden, but that doesn't stop the random vertical stretching of all other components completely breaking the entire layout.

**Comment by thisprojects** [comment] 2023-03-22 19:56
@gabek 👋 Taking a look, can you plz assign to me? 👍

**Comment by gabek** [comment] 2023-03-22 20:35
Absolutely!

**Comment by gabek** [comment] 2023-04-08 00:17
@thisprojects Have any thoughts on the big picture solutions to the layout? If not, I'm thinking about splitting up the layouts into desktop-online, desktop-offline, mobile-online and mobile-offline because I don't currently have a solution to keep a single layout to make them all work, unfortunately.

**Comment by thisprojects** [comment] 2023-04-08 19:31
@gabek Heya Gabe, hard to say without knowing the exact requirements for each section. I would be tempted to keep desktop-offline and mobile-offline the same, can you clarify what the differences in requirements are between the two?

**Comment by gabek** [comment] 2023-04-09 22:08
It's all the scrolling requirements with the tabbed content on mobile that really cause the problems. 

- On mobile the tabbed content should scroll independently without allowing the rest of the page to scroll, allowing the video to stay visible and viewable at the top of the screen.
- Sometimes there's multiple tabs. Sometimes there's zero tabs. It depends on how the server is configured and if the stream is live and chat is enabled. Right now when there's zero tabs the page on mobile can't scroll at all.
- Chat is a tab on mobile, but not a tab on desktop. Having a mobile page where the video is always visible, and the chat is always visible, and handles the mobile keyboard properly has been a challenge.

**Comment by thisprojects** [comment] 2023-04-12 18:52
Thanks Gabe. What I'd recommend is ditching the tabs on portrait mobile altogether. Maybe display the tab content as a column of cards instead. When online :- I'd recommend fixing the stream to the top of the screen. For the chat, I'm thinking the best thing would be some kind of toggle-able transparency gradient. When chat is toggled off, you would only be able to see maybe one or two lines of the chat,  below the stream. When chat is toggled on, you can see the whole of the chat. The chat would basically be like a transparent modal. The whole page should scroll when the chat is toggled off, with the stream remaining `fixed` to the top of the screen regardless of scroll position. This removes the need to `lock` scrolling on the page and should deliver a better user experience. What are your thoughts?

**Comment by gabek** [comment] 2023-04-12 20:51
Honestly I'm not sure. I can't imagine what this column of cards would look like or how you would be able to quickly navigate through them. Plus the same problems would occur given the video is still pinned to the top, but only the bottom is scrollable. That's already how it is, but is causing problems.

It would also completely differentiate desktop and mobile, since mobile would still have tabs. This would double the complexity of the web app and make future features more difficult to build since they'd have to be built with two different layouts.

I think it has to do more with the pinning the video to the top that is the problem, since that's requiring the locking of the body, like you mentioned. The tabs are just a side effect. If the page just scrolled like any other page did then I think all these considerations of certain sections being allowed to scroll and other sections not allowed to scroll wouldn't be an issue.

**Comment by thisprojects** [comment] 2023-04-14 12:33
Setting the stream with a position of `fixed` will negate the need to have the page scroll locked. The stream will always be fixed to the top of the page, with the content scrolling below it. If thats the biggest issue we face, perhaps the problem isn't as bad as first thought. 

I've got some time this weekend to work on this task, I suggest (as a start point) we sort out the offline experience so that the horizontal spacing bugs are fixed and so that the offline desktop and offline mobile experience are as similar as possible (for simplicities sake). I'll then remove the scroll locking behaviour and set the stream to be fixed at the top of the page, for mobile-online. Then see where we go from there? Any thoughts?

**Comment by gabek** [comment] 2023-04-14 21:22
That sounds great! Feel free to ping me if you want to chat about any thoughts while you're looking through it.

**Comment by thisprojects** [comment] 2023-04-17 11:02
Heya @gabek,  I think this branch fixes the issues you have outline. Take a look and let me know if theres anything I've missed. I'll do a bit of component refactoring if it works as expected.  https://github.com/owncast/owncast/pull/2863

**Closed as completed** 2023-04-26 22:31 UTC
Labels: bug, good first issue, Web frontend
