### ISSUE TITLE
"Live" label is drawn above navigation bar in Mobile

### ISSUE THREAD

**Issue by germainelee** [owncast/owncast#3746] opened 2024-05-27 19:58 UTC
### Share your bug report, feature request, or comment.

Currently in mobile view, "Live" label is drawn above navigation bar and partially covers the "About Owncast" button. Please see image attached for how it looks.

![image](https://github.com/owncast/owncast/assets/118464031/591a2ecc-5a76-4024-bf6f-cd5ae51daf6d)

**Expected behavior:**
It should be behind the navigation bar like in desktop.
![image](https://github.com/owncast/owncast/assets/118464031/2865a0d2-696f-4219-9d2b-3dcce71f843d)

Thanks!

**Comment by gabek** [comment] 2024-05-28 16:06
Duplicate of https://github.com/owncast/owncast/issues/2730. Going to close this one.

**Closed as not planned** 2024-05-28 16:07 UTC
